# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7f28958a6ef5f326b44f3a984530115b154100c753126042f46ee4dc61b7ce14bec6a416ff0801f066c6d2e188f3ba1b971e147a3d0b1089fbdde62ea0ee504

test:
  secret_key_base: a9de334733c3d2c4c3bcf9909c0fa408f10abfd1f9ff08e06d7c6f3caa0bbd0a054bd4a82e846c6b61992c0bc5e762ff89d680470fbac15bf3a743ab10e66bd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
